"""视频下载工具 - 整合 you-get、bili23-downloader 和 yt-dlp"""
import logging
import sys
import json
import os
import subprocess
from pathlib import Path
from typing import Optional, Dict, Any, List, Callable
from abc import ABC, abstractmethod

from backend.core.agent.tools.base import Tool, ToolResult, ToolParameter
from shared.platform_utils import normalize_output_dir

logger = logging.getLogger(__name__)


# ============================================================================
# Cookies 处理函数
# ============================================================================

def _load_cookies_from_file(cookies_file: str) -> Optional[str]:
    """从文件加载 cookies
    
    Args:
        cookies_file: Cookies 文件路径（Netscape 格式或 JSON 格式）
    
    Returns:
        Cookies 文件路径（如果有效），否则返回 None
    """
    try:
        cookies_path = Path(cookies_file)
        if not cookies_path.exists():
            logger.warning(f"Cookies 文件不存在: {cookies_file}")
            return None
        
        # 检查文件格式
        with open(cookies_path, 'r', encoding='utf-8') as f:
            first_line = f.readline().strip()
            # Netscape 格式通常以 "# Netscape HTTP Cookie File" 开头
            # JSON 格式以 "[" 或 "{" 开头
            if first_line.startswith('#') or first_line.startswith('[') or first_line.startswith('{'):
                logger.info(f"成功加载 cookies 文件: {cookies_file}")
                return str(cookies_path)
            else:
                logger.warning(f"Cookies 文件格式可能不正确: {cookies_file}")
                return None
    except Exception as e:
        logger.error(f"加载 cookies 文件失败: {e}")
        return None


def _extract_cookies_from_browser(browser: str, domain: str = 'bilibili.com') -> Optional[str]:
    """从浏览器提取 cookies
    
    Args:
        browser: 浏览器名称（'chrome', 'firefox', 'safari', 'edge'）
        domain: 域名（默认 'bilibili.com'）
    
    Returns:
        临时 cookies 文件路径（如果成功），否则返回 None
    """
    try:
        import browser_cookie3  # type: ignore
    except ImportError:
        logger.warning("browser_cookie3 未安装，无法从浏览器提取 cookies。请运行: pip install browser-cookie3")
        return None
    except Exception as e:
        logger.error(f"导入 browser_cookie3 失败: {e}")
        return None
    
    try:
        import tempfile
        
        # 根据浏览器类型选择提取方法
        if browser.lower() == 'chrome':
            cookies = browser_cookie3.chrome(domain_name=domain)
        elif browser.lower() == 'firefox':
            cookies = browser_cookie3.firefox(domain_name=domain)
        elif browser.lower() == 'safari':
            cookies = browser_cookie3.safari(domain_name=domain)
        elif browser.lower() == 'edge':
            cookies = browser_cookie3.edge(domain_name=domain)
        else:
            logger.warning(f"不支持的浏览器: {browser}")
            return None
        
        if not cookies:
            logger.warning(f"从 {browser} 中未找到 {domain} 的 cookies")
            return None
        
        # 创建临时文件（Netscape 格式）
        temp_file = tempfile.NamedTemporaryFile(mode='w', suffix='.txt', delete=False)
        temp_file.write("# Netscape HTTP Cookie File\n")
        temp_file.write("# This file was generated by video_downloader_tool\n\n")
        
        for cookie in cookies:
            # Netscape 格式: domain, flag, path, secure, expiration, name, value
            domain_str = cookie.domain
            flag = 'TRUE' if domain_str.startswith('.') else 'FALSE'
            path = cookie.path or '/'
            secure = 'TRUE' if cookie.secure else 'FALSE'
            expiration = str(int(cookie.expires)) if cookie.expires else '0'
            name = cookie.name
            value = cookie.value
            
            temp_file.write(f"{domain_str}\t{flag}\t{path}\t{secure}\t{expiration}\t{name}\t{value}\n")
        
        temp_file.close()
        logger.info(f"成功从 {browser} 提取 cookies，保存到: {temp_file.name}")
        return temp_file.name
        
    except Exception as e:
        logger.error(f"从浏览器提取 cookies 失败: {e}")
        return None


# ============================================================================
# 适配器基类
# ============================================================================

class DownloadResult:
    """下载结果"""
    def __init__(self, success: bool, data: Optional[Dict[str, Any]] = None, error: Optional[str] = None):
        self.success = success
        self.data = data or {}
        self.error = error


class DownloaderAdapter(ABC):
    """下载器适配器基类"""
    
    def __init__(self):
        """初始化下载器适配器"""
        self.progress_callback: Optional[Callable] = None
    
    def set_progress_callback(self, callback: Optional[Callable]):
        """设置进度回调函数"""
        self.progress_callback = callback
    
    @abstractmethod
    def is_available(self) -> bool:
        """检查工具是否可用"""
        pass
    
    @abstractmethod
    def download(self, url: str, output_dir: Path, **options) -> DownloadResult:
        """执行下载"""
        pass
    
    @abstractmethod
    def supports_platform(self, url: str) -> bool:
        """检查是否支持该平台"""
        pass
    
    def get_supported_platforms(self) -> List[str]:
        """获取支持的平台列表"""
        return []


# ============================================================================
# 平台检测函数
# ============================================================================

def _detect_platform(url: str) -> str:
    """检测视频平台类型"""
    url_lower = url.lower()
    
    if 'bilibili.com' in url_lower or 'b23.tv' in url_lower:
        return 'bilibili'
    elif 'youtube.com' in url_lower or 'youtu.be' in url_lower:
        return 'youtube'
    elif 'youku.com' in url_lower:
        return 'youku'
    elif 'iqiyi.com' in url_lower:
        return 'iqiyi'
    elif 'qq.com' in url_lower and 'video' in url_lower:
        return 'tencent'
    elif 'twitter.com' in url_lower or 'x.com' in url_lower:
        return 'twitter'
    elif 'facebook.com' in url_lower:
        return 'facebook'
    else:
        return 'unknown'


# ============================================================================
# YouGetDownloader 适配器
# ============================================================================

def _get_you_get_path() -> Path:
    """获取 you-get 路径"""
    current_file = Path(__file__).resolve()
    # video_downloader_tool.py 在 backend/core/agent/tools/builtin/
    # 向上找到包含 backend 目录的父目录，然后取其父目录作为项目根
    current = current_file.parent
    while current.name != 'backend' and len(current.parts) > 1:
        current = current.parent
    if current.name == 'backend':
        project_root = current.parent
    else:
        # 如果找不到，使用向上5级的方式（向后兼容）
        project_root = current_file.parent.parent.parent.parent.parent
    return project_root / "backend" / "externals" / "you-get"


class YouGetDownloader(DownloaderAdapter):
    """you-get 适配器"""
    
    def is_available(self) -> bool:
        """检查 you-get 是否可用
        
        注意：不直接导入模块，避免与 subprocess 调用时的模块冲突
        """
        try:
            you_get_path = _get_you_get_path()
            if not you_get_path.exists():
                return False
            
            # 检查是否有 you_get 模块或 src/you_get 目录
            you_get_module = you_get_path / "you_get"
            you_get_src = you_get_path / "src" / "you_get"
            if not you_get_module.exists() and not you_get_src.exists():
                return False
            
            # 不导入模块，只检查文件是否存在（避免模块冲突）
            # 通过尝试运行命令来检查是否可用（使用超时避免阻塞）
            import subprocess
            import os
            try:
                # 使用 sys.executable 确保使用正确的 Python 解释器
                python_exe = sys.executable
                
                # 设置环境变量，确保能找到模块
                env = os.environ.copy()
                if you_get_src.exists():
                    env['PYTHONPATH'] = str(you_get_path / "src")
                elif you_get_module.exists():
                    env['PYTHONPATH'] = str(you_get_path)
                
                # 使用 python -m you_get --version 来检查（不导入模块）
                result = subprocess.run(
                    [python_exe, '-m', 'you_get', '--version'],
                    cwd=str(you_get_path),
                    capture_output=True,
                    text=True,
                    timeout=5,
                    env=env
                )
                # 即使返回非零退出码，只要命令能运行就认为可用
                # 如果命令不存在或模块不存在，会抛出 FileNotFoundError 或其他异常
                return True
            except (subprocess.TimeoutExpired, FileNotFoundError):
                return False
            except Exception:
                # 其他异常（如模块导入错误），但文件存在，仍然认为可用
                # 因为可能是运行时环境问题，不是模块不存在
                return you_get_module.exists() or you_get_src.exists()
        except Exception:
            return False
    
    def supports_platform(self, url: str) -> bool:
        """you-get 支持大部分平台"""
        platform = _detect_platform(url)
        return platform != 'unknown'
    
    def download(self, url: str, output_dir: Path, **options) -> DownloadResult:
        """使用 you-get 下载"""
        try:
            you_get_path = _get_you_get_path()
            if not you_get_path.exists():
                return DownloadResult(success=False, error="you-get not found")
            
            import subprocess
            import os
            
            # 设置环境变量，确保 you-get 能找到模块（避免模块导入冲突）
            env = os.environ.copy()
            you_get_module = you_get_path / "you_get"
            you_get_src = you_get_path / "src" / "you_get"
            
            if you_get_src.exists():
                # 如果存在 src 目录，添加到 PYTHONPATH
                src_path = you_get_path / "src"
                if 'PYTHONPATH' in env:
                    env['PYTHONPATH'] = str(src_path) + os.pathsep + env['PYTHONPATH']
                else:
                    env['PYTHONPATH'] = str(src_path)
            elif you_get_module.exists():
                # 否则使用 you_get_path
                if 'PYTHONPATH' in env:
                    env['PYTHONPATH'] = str(you_get_path) + os.pathsep + env['PYTHONPATH']
                else:
                    env['PYTHONPATH'] = str(you_get_path)
            
            # 使用独立的 Python 进程调用 you-get（完全隔离，避免模块冲突）
            # 使用 sys.executable 确保使用当前 Python 解释器
            import sys as sys_module
            python_exe = sys_module.executable
            
            # 使用 -I 参数（隔离模式）或 -S 参数（不导入 site 模块）来避免模块冲突
            # -I 参数会忽略 PYTHONPATH 和 site-packages，但我们需要 PYTHONPATH，所以使用 -S
            # 但实际上，由于我们在 env 中设置了 PYTHONPATH，所以直接使用即可
            # 关键是要确保使用独立的进程，并且不导入当前进程中的模块
            cmd = [python_exe, '-m', 'you_get']
            
            # 输出目录
            cmd.extend(['-o', str(output_dir)])
            
            # you-get 不支持 -q 参数，只支持 -f 格式选择
            # 如果指定了 format，使用 -f 参数
            if options.get('format'):
                cmd.extend(['-f', str(options['format'])])
            # 如果指定了 quality，尝试转换为 format
            # you-get 的 format 参数格式：stream_id 或 stream_id+stream_id（如 "80" 或 "80+64"）
            # 对于 quality 参数，我们需要忽略它，因为 you-get 不支持直接的质量选择
            # 用户可以通过 format 参数指定具体的流 ID
            # 注意：quality 参数在 you-get 中不被支持，这里忽略它
            
            # URL
            cmd.append(url)
            
            # 执行（使用环境变量，避免模块导入冲突）
            # 关键：使用独立的 Python 进程，并且确保 PYTHONPATH 正确设置
            # 这样即使当前进程中有 you_get 模块，子进程也不会受到影响
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                cwd=str(you_get_path),
                env=env,
                # 确保使用独立的进程组，避免继承父进程的模块状态
                start_new_session=False  # macOS 上 start_new_session 可能不可用
            )
            
            if result.returncode == 0:
                logger.info(f"you-get 下载成功: {url}")
                return DownloadResult(
                    success=True,
                    data={'tool': 'you-get', 'output_dir': str(output_dir)}
                )
            else:
                # 合并 stderr 和 stdout，因为 you-get 可能将错误信息输出到 stdout
                error_output = (result.stderr or "") + (result.stdout or "")
                if not error_output.strip():
                    error_output = "Unknown error"
                
                # 过滤掉 RuntimeWarning（这只是警告，不影响功能）
                error_lines = error_output.split('\n')
                filtered_lines = []
                for line in error_lines:
                    # 跳过 RuntimeWarning 行
                    if 'RuntimeWarning' in line or 'frozen runpy' in line:
                        continue
                    filtered_lines.append(line)
                error_output = '\n'.join(filtered_lines).strip()
                
                logger.error(f"you-get 下载失败: {error_output}")
                
                # 识别特定的错误类型并提供针对性的建议
                if 'LOGIN_REQUIRED' in error_output or '登录' in error_output or 'login' in error_output.lower() or '機械人' in error_output or '机器人' in error_output:
                    # 登录要求错误
                    detailed_error = (
                        f"需要登录验证\n\n"
                        f"平台要求登录以验证您不是机器人。\n\n"
                        f"解决方案：\n"
                        f"1. 使用 cookies：\n"
                        f"   - 使用 cookies_from_browser 参数从浏览器提取 cookies\n"
                        f"   - 或使用 cookies_file 参数提供 cookies 文件\n"
                        f"   - 示例：cookies_from_browser='chrome'\n\n"
                        f"2. 尝试使用 yt-dlp（可能支持更好的认证）：\n"
                        f"   - 设置 preferred_tool='yt-dlp'\n"
                        f"   - yt-dlp 对 cookies 的支持更好\n\n"
                        f"3. 手动登录：\n"
                        f"   - 在浏览器中登录相应平台\n"
                        f"   - 然后使用 cookies_from_browser 提取 cookies\n\n"
                        f"原始错误: {error_output}"
                    )
                elif 'RuntimeWarning' in result.stderr or 'frozen runpy' in result.stderr:
                    # 模块冲突警告（已过滤，但保留建议）
                    detailed_error = (
                        f"you-get 执行失败\n\n"
                        f"注意：检测到模块导入警告（已自动过滤），但这不影响功能。\n\n"
                        f"如果下载失败，建议：\n"
                        f"1. 尝试使用 yt-dlp 工具（设置 preferred_tool='yt-dlp'）\n"
                        f"2. 检查 URL 是否正确\n"
                        f"3. 检查网络连接\n\n"
                        f"错误信息: {error_output}"
                    )
                else:
                    # 其他错误
                    detailed_error = (
                        f"you-get 下载失败\n\n"
                        f"错误信息: {error_output}\n\n"
                        f"建议：\n"
                        f"1. 检查 URL 是否正确\n"
                        f"2. 检查网络连接\n"
                        f"3. 如果视频需要登录，使用 cookies_from_browser 或 cookies_file 参数\n"
                        f"4. 尝试使用 yt-dlp 工具（设置 preferred_tool='yt-dlp'）\n"
                    )
                
                return DownloadResult(
                    success=False,
                    error=detailed_error
                )
        except Exception as e:
            return DownloadResult(success=False, error=f"you-get error: {str(e)}")


# ============================================================================
# Bili23Downloader 适配器
# ============================================================================

def _get_bili23_path() -> Path:
    """获取 bili23-downloader 路径"""
    current_file = Path(__file__).resolve()
    # video_downloader_tool.py 在 backend/core/agent/tools/builtin/
    # 向上找到包含 backend 目录的父目录，然后取其父目录作为项目根
    current = current_file.parent
    while current.name != 'backend' and len(current.parts) > 1:
        current = current.parent
    if current.name == 'backend':
        project_root = current.parent
    else:
        # 如果找不到，使用向上5级的方式（向后兼容）
        project_root = current_file.parent.parent.parent.parent.parent
    return project_root / "backend" / "externals" / "bili23-downloader"


class Bili23Downloader(DownloaderAdapter):
    """bili23-downloader 适配器"""
    
    def is_available(self) -> bool:
        """检查 bili23-downloader 是否可用"""
        try:
            bili23_path = _get_bili23_path()
            return bili23_path.exists()
        except Exception:
            return False
    
    def supports_platform(self, url: str) -> bool:
        """bili23-downloader 只支持 Bilibili"""
        return _detect_platform(url) == 'bilibili'
    
    def download(self, url: str, output_dir: Path, **options) -> DownloadResult:
        """使用 bili23-downloader 下载"""
        try:
            bili23_path = _get_bili23_path()
            if not bili23_path.exists():
                return DownloadResult(success=False, error="bili23-downloader not found")
            
            # bili23-downloader 是 GUI 应用，没有简单的 CLI 接口
            # 暂时降级到使用 yt-dlp 或 you-get
            # TODO: 未来可以实现通过 Python API 直接调用 bili23-downloader 的核心模块
            
            # 尝试使用 yt-dlp 作为降级方案
            yt_dlp = YtDlpDownloader()
            if yt_dlp.is_available():
                logger.info("bili23-downloader not available, falling back to yt-dlp")
                return yt_dlp.download(url, output_dir, **options)
            
            # 降级到 you-get
            you_get = YouGetDownloader()
            if you_get.is_available():
                logger.info("bili23-downloader not available, falling back to you-get")
                return you_get.download(url, output_dir, **options)
            
            return DownloadResult(
                success=False,
                error="bili23-downloader integration not yet implemented, and no fallback available"
            )
        except Exception as e:
            return DownloadResult(success=False, error=f"bili23-downloader error: {str(e)}")


# ============================================================================
# YtDlpDownloader 适配器
# ============================================================================

def _get_yt_dlp_path() -> Path:
    """获取 yt-dlp 路径"""
    current_file = Path(__file__).resolve()
    # video_downloader_tool.py 在 backend/core/agent/tools/builtin/
    # 向上找到包含 backend 目录的父目录，然后取其父目录作为项目根
    current = current_file.parent
    while current.name != 'backend' and len(current.parts) > 1:
        current = current.parent
    if current.name == 'backend':
        project_root = current.parent
    else:
        # 如果找不到，使用向上5级的方式（向后兼容）
        project_root = current_file.parent.parent.parent.parent.parent
    return project_root / "backend" / "externals" / "yt-dlp"


def _get_ffmpeg_path() -> Path:
    """获取 FFmpeg 可执行文件路径"""
    current_file = Path(__file__).resolve()
    # video_downloader_tool.py 在 backend/core/agent/tools/builtin/
    # 向上找到包含 backend 目录的父目录，然后取其父目录作为项目根
    current = current_file.parent
    while current.name != 'backend' and len(current.parts) > 1:
        current = current.parent
    if current.name == 'backend':
        project_root = current.parent
    else:
        # 如果找不到，使用向上5级的方式（向后兼容）
        project_root = current_file.parent.parent.parent.parent.parent
    return project_root / "backend" / "externals" / "ffmpeg" / "build" / "bin" / "ffmpeg"


def _get_ffmpeg_bin_dir() -> Path:
    """获取 FFmpeg bin 目录路径"""
    current_file = Path(__file__).resolve()
    # video_downloader_tool.py 在 backend/core/agent/tools/builtin/
    # 向上找到包含 backend 目录的父目录，然后取其父目录作为项目根
    current = current_file.parent
    while current.name != 'backend' and len(current.parts) > 1:
        current = current.parent
    if current.name == 'backend':
        project_root = current.parent
    else:
        # 如果找不到，使用向上5级的方式（向后兼容）
        project_root = current_file.parent.parent.parent.parent.parent
    return project_root / "backend" / "externals" / "ffmpeg" / "build" / "bin"


class YtDlpDownloader(DownloaderAdapter):
    """yt-dlp 适配器"""
    
    def is_available(self) -> bool:
        """检查 yt-dlp 是否可用，并检查版本"""
        try:
            yt_dlp_path = _get_yt_dlp_path()
            if not yt_dlp_path.exists():
                logger.debug("yt-dlp path does not exist")
                return False
            
            # 尝试导入 yt_dlp
            if str(yt_dlp_path) not in sys.path:
                sys.path.insert(0, str(yt_dlp_path))
            
            import yt_dlp  # type: ignore
            
            # 检查版本并记录
            try:
                version = yt_dlp.version.__version__
                logger.info(f"yt-dlp version: {version}")
                # 可以在这里添加版本检查逻辑，提示用户更新
                # 例如：检查版本是否过旧，建议更新
            except Exception:
                pass  # 版本检查失败不影响可用性
            
            return True
        except Exception as e:
            logger.debug(f"yt-dlp availability check failed: {e}")
            return False
    
    def supports_platform(self, url: str) -> bool:
        """yt-dlp 支持大部分平台"""
        platform = _detect_platform(url)
        return platform != 'unknown'
    
    def download(self, url: str, output_dir: Path, **options) -> DownloadResult:
        """使用 yt-dlp 下载"""
        try:
            yt_dlp_path = _get_yt_dlp_path()
            if not yt_dlp_path.exists():
                return DownloadResult(success=False, error="yt-dlp not found")
            
            # 添加路径
            if str(yt_dlp_path) not in sys.path:
                sys.path.insert(0, str(yt_dlp_path))
            
            import yt_dlp  # type: ignore
            import os
            
            # 尝试使用项目中的 FFmpeg（如果存在）
            ffmpeg_bin_dir = _get_ffmpeg_bin_dir()
            use_local_ffmpeg = ffmpeg_bin_dir.exists()
            
            ydl_opts: Dict[str, Any] = {
                'outtmpl': str(output_dir / '%(title)s.%(ext)s'),
            }
            
            # 处理 cookies
            cookies_file = options.get('cookies_file')
            cookies_from_browser = options.get('cookies_from_browser')
            
            if cookies_file:
                # 从文件加载 cookies
                cookies_path = _load_cookies_from_file(cookies_file)
                if cookies_path:
                    ydl_opts['cookiefile'] = cookies_path
                    logger.info(f"使用 cookies 文件: {cookies_path}")
            elif cookies_from_browser:
                # 从浏览器提取 cookies
                domain = 'bilibili.com' if 'bilibili.com' in url.lower() or 'b23.tv' in url.lower() else None
                cookies_path = _extract_cookies_from_browser(cookies_from_browser, domain or '')
                if cookies_path:
                    ydl_opts['cookiefile'] = cookies_path
                    logger.info(f"从 {cookies_from_browser} 提取 cookies: {cookies_path}")
            
            # 对于哔哩哔哩，添加必要的 headers 以避免 412 错误
            if 'bilibili.com' in url.lower() or 'b23.tv' in url.lower():
                # 使用更真实的浏览器 headers（模拟 Chrome 浏览器）
                ydl_opts['http_headers'] = {
                    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
                    'Referer': 'https://www.bilibili.com/',
                    'Origin': 'https://www.bilibili.com',
                    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
                    'Accept-Language': 'zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7',
                    'Accept-Encoding': 'gzip, deflate, br',
                    'Connection': 'keep-alive',
                    'Upgrade-Insecure-Requests': '1',
                    'Sec-Fetch-Dest': 'document',
                    'Sec-Fetch-Mode': 'navigate',
                    'Sec-Fetch-Site': 'none',
                    'Sec-Fetch-User': '?1',
                    'Cache-Control': 'max-age=0',
                    'DNT': '1',
                }
                # 添加额外的 yt-dlp 选项来绕过反爬虫
                ydl_opts['extractor_args'] = {
                    'bilibili': {
                        'username': None,  # 如果需要登录，可以在这里设置
                        'password': None,
                    }
                }
                # 尝试使用更宽松的提取器设置
                ydl_opts['no_check_certificate'] = False
                ydl_opts['ignoreerrors'] = False
                # 添加重试机制
                ydl_opts['retries'] = 3
                # 添加延迟，避免请求过快
                ydl_opts['sleep_interval'] = 1
                ydl_opts['sleep_interval_requests'] = 1
            
            # 如果使用本地 FFmpeg，设置路径
            if use_local_ffmpeg:
                ydl_opts['ffmpeg_location'] = str(ffmpeg_bin_dir)
            
            # 只下载字幕
            if options.get('download_subtitle_only'):
                ydl_opts['writesubtitles'] = True  # type: ignore
                ydl_opts['writeautomaticsub'] = True  # type: ignore
                ydl_opts['skip_download'] = True  # type: ignore
                if options.get('subtitle_languages'):
                    ydl_opts['subtitleslangs'] = options['subtitle_languages']
            
            # 只提取音频
            elif options.get('extract_audio_only'):
                ydl_opts['format'] = 'bestaudio/best'
                
                # 检查 FFmpeg 是否支持 MP3 编码器
                audio_format = options.get('audio_format', 'mp3')
                if audio_format.lower() == 'mp3':
                    # 检查 MP3 编码器是否可用
                    ffmpeg_path = _get_ffmpeg_path()
                    if ffmpeg_path.exists():
                        try:
                            import subprocess
                            result = subprocess.run(
                                [str(ffmpeg_path), '-encoders'],
                                capture_output=True,
                                text=True,
                                timeout=5
                            )
                            # 检查是否支持 libmp3lame 编码器
                            if 'libmp3lame' not in result.stdout:
                                logger.warning("FFmpeg 不支持 MP3 编码器（libmp3lame），改用 AAC 格式")
                                audio_format = 'aac'
                        except Exception as e:
                            logger.warning(f"无法检查 FFmpeg 编码器，改用 AAC 格式: {e}")
                            audio_format = 'aac'
                    else:
                        # 如果本地 FFmpeg 不存在，检查系统 FFmpeg
                        try:
                            import subprocess
                            result = subprocess.run(
                                ['ffmpeg', '-encoders'],
                                capture_output=True,
                                text=True,
                                timeout=5
                            )
                            if 'libmp3lame' not in result.stdout:
                                logger.warning("系统 FFmpeg 不支持 MP3 编码器（libmp3lame），改用 AAC 格式")
                                audio_format = 'aac'
                        except Exception:
                            # 如果检查失败，默认使用 AAC（更通用）
                            logger.warning("无法检查 FFmpeg 编码器，改用 AAC 格式")
                            audio_format = 'aac'
                
                ydl_opts['postprocessors'] = [{  # type: ignore
                    'key': 'FFmpegExtractAudio',
                    'preferredcodec': audio_format,
                    'preferredquality': options.get('audio_quality', '192'),
                }]
            else:
                # 正常下载视频
                if options.get('quality'):
                    ydl_opts['format'] = self._convert_quality_to_yt_dlp_format(options['quality'])
                if options.get('download_subtitle'):
                    ydl_opts['writesubtitles'] = True  # type: ignore
                    if options.get('subtitle_languages'):
                        ydl_opts['subtitleslangs'] = options['subtitle_languages']
            
            # 临时设置 PATH 环境变量（如果使用本地 FFmpeg）
            old_path = None
            if use_local_ffmpeg:
                old_path = os.environ.get('PATH', '')
                os.environ['PATH'] = str(ffmpeg_bin_dir) + os.pathsep + old_path
            
            try:
                logger.info(f"开始使用 yt-dlp 下载: {url}")
                # 记录配置信息（不包含敏感信息）
                debug_opts = {k: v for k, v in ydl_opts.items() if k not in ['cookiefile']}
                logger.debug(f"yt-dlp 配置: {json.dumps(debug_opts, indent=2, ensure_ascii=False, default=str)}")
                
                # 添加进度钩子（如果设置了进度回调）
                progress_callback = self.progress_callback
                if progress_callback:
                    def progress_hook(d: Dict[str, Any]):
                        """yt-dlp 进度钩子"""
                        if not progress_callback:
                            return
                        if d.get('status') == 'downloading':
                            # 提取进度信息
                            total = d.get('total_bytes') or d.get('total_bytes_estimate')
                            downloaded = d.get('downloaded_bytes', 0)
                            if total and total > 0:
                                progress_percent = int((downloaded / total) * 100)
                                speed = d.get('speed', 0)
                                speed_str = f"{speed / 1024 / 1024:.2f} MB/s" if speed else "未知"
                                message = f"下载中: {progress_percent}% ({speed_str})"
                                # 调用进度回调（适配两种签名）
                                try:
                                    # 尝试传递进度值和消息
                                    progress_callback(progress_percent, message)
                                except TypeError:
                                    # 如果失败，只传递消息
                                    progress_callback(message)
                        elif d.get('status') == 'finished':
                            message = "下载完成"
                            try:
                                progress_callback(100, message)
                            except TypeError:
                                progress_callback(message)
                    
                    ydl_opts['progress_hooks'] = [progress_hook]  # type: ignore
                
                with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                    info = ydl.extract_info(url, download=True)
                    
                    # 提取详细信息
                    result_data = {
                        'tool': 'yt-dlp',
                        'output_dir': str(output_dir),
                        'title': info.get('title', ''),
                        'duration': info.get('duration'),
                        'uploader': info.get('uploader', ''),
                        'upload_date': info.get('upload_date', ''),
                        'view_count': info.get('view_count'),
                        'description': info.get('description', '')[:200] if info.get('description') else '',  # 限制长度
                    }
                    
                    logger.info(f"yt-dlp 下载成功: {result_data.get('title', 'Unknown')} (时长: {result_data.get('duration', 'N/A')}秒)")
                    return DownloadResult(
                        success=True,
                        data=result_data
                    )
            except yt_dlp.utils.DownloadError as e:
                error_msg = str(e)
                logger.error(f"yt-dlp 下载错误: {error_msg}")
                
                # 提供更详细的错误信息和解决建议
                if '412' in error_msg or 'Precondition Failed' in error_msg:
                    # 如果是 Bilibili 且没有使用 cookies，尝试自动从浏览器提取
                    is_bilibili = 'bilibili.com' in url.lower() or 'b23.tv' in url.lower()
                    auto_cookies_tried = False
                    auto_cookies_path = None
                    
                    if is_bilibili and not cookies_file and not cookies_from_browser:
                        # 自动尝试从常见浏览器提取 cookies
                        logger.info("检测到 HTTP 412 错误，尝试自动从浏览器提取 cookies...")
                        for browser in ['chrome', 'firefox', 'safari', 'edge']:
                            try:
                                cookies_path = _extract_cookies_from_browser(browser, 'bilibili.com')
                                if cookies_path:
                                    auto_cookies_path = cookies_path
                                    auto_cookies_tried = True
                                    logger.info(f"成功从 {browser} 提取 cookies，重试下载...")
                                    
                                    # 使用提取的 cookies 重试（使用完整的 ydl_opts 配置）
                                    retry_opts = ydl_opts.copy()
                                    retry_opts['cookiefile'] = cookies_path
                                    
                                    try:
                                        with yt_dlp.YoutubeDL(retry_opts) as ydl:
                                            info = ydl.extract_info(url, download=True)
                                            
                                            # 提取详细信息
                                            result_data = {
                                                'tool': 'yt-dlp',
                                                'output_dir': str(output_dir),
                                                'title': info.get('title', ''),
                                                'duration': info.get('duration'),
                                                'uploader': info.get('uploader', ''),
                                                'cookies_auto_extracted': True,
                                                'cookies_source': browser
                                            }
                                            
                                            logger.info("使用自动提取的 cookies 下载成功")
                                            return DownloadResult(
                                                success=True,
                                                data=result_data
                                            )
                                    except Exception as retry_error:
                                        logger.warning(f"使用自动提取的 cookies 重试失败: {retry_error}")
                                        # 继续尝试下一个浏览器
                                        continue
                            except Exception as e:
                                logger.debug(f"从 {browser} 提取 cookies 失败: {e}")
                                continue
                    
                    # 构建错误信息
                    detailed_error = (
                        f"HTTP 412 错误（Precondition Failed）\n"
                        f"这通常是由于哔哩哔哩的反爬虫机制导致的。\n\n"
                    )
                    
                    if auto_cookies_tried:
                        if auto_cookies_path:
                            detailed_error += (
                                f"已尝试自动从浏览器提取 cookies，但下载仍然失败。\n\n"
                            )
                        else:
                            detailed_error += (
                                f"已尝试自动从浏览器提取 cookies，但未找到有效的 cookies。\n\n"
                            )
                    
                    detailed_error += (
                        f"建议解决方案：\n"
                        f"1. 使用 cookies（推荐）：\n"
                        f"   - 使用 cookies_from_browser 参数从浏览器提取 cookies\n"
                        f"   - 示例：cookies_from_browser='chrome'\n"
                        f"   - 或使用 cookies_file 参数提供 cookies 文件\n\n"
                        f"2. 更新 yt-dlp：确保使用最新版本（当前版本: {yt_dlp.version.__version__ if hasattr(yt_dlp, 'version') else 'unknown'}）\n\n"
                        f"3. 尝试其他工具：设置 preferred_tool='you-get' 使用 you-get 工具\n\n"
                        f"4. 检查网络：确保网络连接正常，没有被防火墙拦截\n\n"
                        f"原始错误: {error_msg}"
                    )
                    return DownloadResult(success=False, error=detailed_error)
                elif '403' in error_msg or 'Forbidden' in error_msg:
                    detailed_error = (
                        f"HTTP 403 错误（Forbidden）\n"
                        f"访问被拒绝，可能需要登录或使用 cookies。\n\n"
                        f"建议解决方案：\n"
                        f"1. 使用 cookies：通过 cookies_file 或 cookies_from_browser 参数提供 cookies\n"
                        f"2. 检查视频权限：确保视频是公开的，或者您有访问权限\n"
                        f"3. 如果是 YouTube，可能需要登录验证（使用 cookies）\n\n"
                        f"原始错误: {error_msg}"
                    )
                    return DownloadResult(success=False, error=detailed_error)
                elif 'LOGIN_REQUIRED' in error_msg or 'login required' in error_msg.lower() or '登录' in error_msg or '機械人' in error_msg or '机器人' in error_msg:
                    detailed_error = (
                        f"需要登录验证\n\n"
                        f"平台要求登录以验证您不是机器人。\n\n"
                        f"解决方案：\n"
                        f"1. 使用 cookies（推荐）：\n"
                        f"   - 使用 cookies_from_browser 参数从浏览器提取 cookies\n"
                        f"   - 或使用 cookies_file 参数提供 cookies 文件\n"
                        f"   - 示例：cookies_from_browser='chrome'\n\n"
                        f"2. 手动登录：\n"
                        f"   - 在浏览器中登录相应平台（如 YouTube）\n"
                        f"   - 然后使用 cookies_from_browser 提取 cookies\n\n"
                        f"3. 尝试其他工具：\n"
                        f"   - 设置 preferred_tool='yt-dlp' 使用 yt-dlp（对 cookies 支持更好）\n\n"
                        f"原始错误: {error_msg}"
                    )
                    return DownloadResult(success=False, error=detailed_error)
                elif '404' in error_msg or 'Not Found' in error_msg:
                    detailed_error = (
                        f"HTTP 404 错误（Not Found）\n"
                        f"视频不存在或已被删除。\n\n"
                        f"原始错误: {error_msg}"
                    )
                    return DownloadResult(success=False, error=detailed_error)
                else:
                    # 其他错误，提供通用建议
                    detailed_error = (
                        f"yt-dlp 下载失败\n\n"
                        f"错误信息: {error_msg}\n\n"
                        f"建议：\n"
                        f"1. 检查 URL 是否正确\n"
                        f"2. 检查网络连接\n"
                        f"3. 尝试使用 cookies（如果需要登录）\n"
                        f"4. 更新 yt-dlp 到最新版本\n"
                    )
                    return DownloadResult(success=False, error=detailed_error)
            except Exception as e:
                error_msg = str(e)
                logger.error(f"yt-dlp 执行异常: {error_msg}", exc_info=True)
                return DownloadResult(success=False, error=f"yt-dlp 执行异常: {error_msg}")
            finally:
                # 恢复 PATH
                if old_path is not None:
                    os.environ['PATH'] = old_path
        except Exception as e:
            error_msg = str(e)
            logger.error(f"yt-dlp download 方法执行异常: {error_msg}", exc_info=True)
            return DownloadResult(success=False, error=f"yt-dlp 执行异常: {error_msg}")
    
    def _convert_quality_to_yt_dlp_format(self, quality: str) -> str:
        """转换质量参数到 yt-dlp 格式"""
        quality_map = {
            'best': 'best',
            'worst': 'worst',
            '1080p': 'best[height<=1080]',
            '720p': 'best[height<=720]',
            '480p': 'best[height<=480]',
            '360p': 'best[height<=360]',
            '240p': 'best[height<=240]',
        }
        return quality_map.get(quality, 'best')


# ============================================================================
# 工具选择函数
# ============================================================================

def _select_downloader(url: str, preferred: str = 'auto', **options) -> DownloaderAdapter:
    """选择下载工具"""
    platform = _detect_platform(url)
    
    # 特殊功能优先使用 yt-dlp
    if options.get('download_subtitle_only') or options.get('extract_audio_only'):
        yt_dlp = YtDlpDownloader()
        if yt_dlp.is_available():
            return yt_dlp
    
    # 用户指定了首选工具
    if preferred == 'bili23' and platform == 'bilibili':
        bili23 = Bili23Downloader()
        if bili23.is_available():
            return bili23
        # 如果不可用，返回它（让错误信息更清晰）
        logger.warning(f"Preferred tool 'bili23' is not available")
        return bili23
    elif preferred == 'yt-dlp':
        yt_dlp = YtDlpDownloader()
        if yt_dlp.is_available():
            return yt_dlp
        # 如果不可用，返回它（让错误信息更清晰）
        logger.warning(f"Preferred tool 'yt-dlp' is not available")
        return yt_dlp
    elif preferred == 'you-get':
        you_get = YouGetDownloader()
        if you_get.is_available():
            return you_get
        # 如果不可用，返回它（让错误信息更清晰）
        logger.warning(f"Preferred tool 'you-get' is not available")
        return you_get
    
    # 自动选择
    if platform == 'bilibili':
        # B 站优先使用 bili23-downloader
        bili23 = Bili23Downloader()
        if bili23.is_available():
            return bili23
        # 对于哔哩哔哩，优先使用 you-get（通常对 B 站支持更好）
        you_get = YouGetDownloader()
        if you_get.is_available():
            return you_get
        # 降级到 yt-dlp
        yt_dlp = YtDlpDownloader()
        if yt_dlp.is_available():
            return yt_dlp
        # 如果都不可用，返回 you-get（即使不可用，让错误信息更清晰）
        return you_get
    elif platform == 'youtube':
        # YouTube 优先使用 yt-dlp
        yt_dlp = YtDlpDownloader()
        if yt_dlp.is_available():
            return yt_dlp
        you_get = YouGetDownloader()
        if you_get.is_available():
            return you_get
        # 如果都不可用，返回 yt-dlp
        return yt_dlp
    else:
        # 其他平台优先使用 yt-dlp
        yt_dlp = YtDlpDownloader()
        if yt_dlp.is_available():
            return yt_dlp
        you_get = YouGetDownloader()
        if you_get.is_available():
            return you_get
        # 如果都不可用，返回 yt-dlp
        return yt_dlp


# ============================================================================
# VideoDownloaderTool 主工具类
# ============================================================================

class VideoDownloaderTool(Tool):
    """视频下载工具"""
    
    def __init__(self):
        """初始化工具"""
        parameters = [
            ToolParameter(
                name="url",
                type="string",
                description="要下载的视频链接。支持短链接（如 b23.tv）和完整 URL。",
                required=True
            ),
            ToolParameter(
                name="output_dir",
                type="string",
                description="视频文件的保存目录。如果不指定，默认保存到系统下载目录。",
                required=False
            ),
            ToolParameter(
                name="quality",
                type="string",
                description="要下载的视频质量。可选值：'best'、'worst'、'1080p'、'720p'、'480p' 等。默认 'best'。",
                required=False,
                default="best",
                enum=["best", "worst", "1080p", "720p", "480p", "360p", "240p"]
            ),
            ToolParameter(
                name="format",
                type="string",
                description="视频文件格式。可选值：'mp4'、'flv'、'webm'、'mkv'、'auto'。",
                required=False,
                enum=["mp4", "flv", "webm", "mkv", "auto"]
            ),
            ToolParameter(
                name="download_subtitle",
                type="boolean",
                description="是否下载视频字幕文件。",
                required=False,
                default=False
            ),
            ToolParameter(
                name="download_thumbnail",
                type="boolean",
                description="是否下载视频封面图片。",
                required=False,
                default=False
            ),
            ToolParameter(
                name="download_danmaku",
                type="boolean",
                description="是否下载 Bilibili 弹幕文件（ASS 格式）。仅对 Bilibili 视频有效。",
                required=False,
                default=False
            ),
            ToolParameter(
                name="download_subtitle_only",
                type="boolean",
                description="是否只下载字幕，不下载视频。",
                required=False,
                default=False
            ),
            ToolParameter(
                name="extract_audio_only",
                type="boolean",
                description="是否只提取音频，不下载视频。",
                required=False,
                default=False
            ),
            ToolParameter(
                name="audio_format",
                type="string",
                description="音频文件格式（仅当 extract_audio_only=true 时有效）。默认 'mp3'。",
                required=False,
                default="mp3",
                enum=["mp3", "m4a", "opus", "wav", "aac"]
            ),
            ToolParameter(
                name="audio_quality",
                type="string",
                description="音频质量（仅当 extract_audio_only=true 时有效）。默认 '192k'。",
                required=False,
                default="192k",
                enum=["128k", "192k", "256k", "320k"]
            ),
            ToolParameter(
                name="subtitle_languages",
                type="array",
                description="要下载的字幕语言代码列表（如 ['en', 'zh']）。",
                required=False
            ),
            ToolParameter(
                name="preferred_tool",
                type="string",
                description="指定优先使用的下载工具。'auto'（自动选择）、'yt-dlp'、'you-get'、'bili23'。",
                required=False,
                default="auto",
                enum=["auto", "yt-dlp", "you-get", "bili23"]
            ),
            ToolParameter(
                name="cookies_file",
                type="string",
                description="Cookies 文件路径（Netscape 格式或 JSON 格式）。用于需要登录的视频。",
                required=False
            ),
            ToolParameter(
                name="cookies_from_browser",
                type="string",
                description="从浏览器提取 cookies。可选值：'chrome'、'firefox'、'safari'、'edge'。需要安装 browser_cookie3 库。",
                required=False,
                enum=["chrome", "firefox", "safari", "edge"]
            ),
        ]
        
        description = (
            "从多个视频平台下载视频文件。"
            "支持 YouTube、Bilibili、优酷、腾讯视频、爱奇艺等多个平台。"
            "对于 Bilibili 视频，支持下载弹幕、字幕、封面等附加内容。"
            "\n\n"
            "功能特点："
            "\n- 自动识别视频平台并选择最佳下载工具"
            "\n- 支持自定义视频质量和格式"
            "\n- Bilibili 视频支持下载弹幕（ASS 格式）、字幕、封面、NFO 元数据"
            "\n- 支持断点续传和多线程下载（Bilibili）"
            "\n- 支持只下载字幕（不下载视频）"
            "\n- 支持只提取音频（不下载视频）"
            "\n- 自动降级策略：如果首选工具失败，自动切换到备用工具"
        )
        
        super().__init__(
            name="video_downloader",
            description=description,
            parameters=parameters
        )
    
    def execute(self, **kwargs) -> ToolResult:
        """执行下载"""
        url = kwargs.get('url')
        if not url:
            return ToolResult(success=False, error="URL is required")
        
        # 规范化输出目录
        output_dir = normalize_output_dir(kwargs.get('output_dir'))
        
        # 选择下载器
        preferred = kwargs.get('preferred_tool', 'auto')
        # 从 kwargs 中移除已单独处理的参数，避免重复传递
        downloader_options = {k: v for k, v in kwargs.items() if k not in ['url', 'output_dir', 'preferred_tool']}
        downloader = _select_downloader(url, preferred, **downloader_options)
        
        if not downloader.is_available():
            return ToolResult(
                success=False,
                error=f"Downloader {downloader.__class__.__name__} is not available"
            )
        
        # 如果工具设置了进度回调，传递给下载器
        if self.progress_callback:
            downloader.set_progress_callback(self.progress_callback)
        
        # 执行下载（使用相同的 downloader_options，不包含 url、output_dir、preferred_tool）
        result = downloader.download(url, output_dir, **downloader_options)
        
        if result.success:
            return ToolResult(
                success=True,
                data=result.data
            )
        else:
            # 尝试降级
            if preferred == 'auto':
                fallback_downloaders = [
                    YouGetDownloader(),
                    YtDlpDownloader(),
                ]
                
                for fallback in fallback_downloaders:
                    if fallback.is_available() and fallback != downloader:
                        logger.info(f"Trying fallback downloader: {fallback.__class__.__name__}")
                        fallback_result = fallback.download(url, output_dir, **downloader_options)
                        if fallback_result.success:
                            return ToolResult(
                                success=True,
                                data=fallback_result.data
                            )
            
            return ToolResult(
                success=False,
                error=result.error or "Download failed"
            )

